### ISSUE TITLE
consider adding travis ci support to github.

### ISSUE THREAD

**Issue by danmarsden** [juacas/moodle-mod_quest#11]
Some of the tests run by the Moodle.org plugins db can be run via travis-ci on each commit in your github repo. Making your code comply with the moodle coding guidelines also makes it much easier for the review team to review your code.
More information on this is here:
https://moodle.org/mod/forum/discuss.php?d=323384

but the short version:
grab this file:
https://github.com/moodlerooms/moodle-plugin-ci/blob/master/.travis.dist.yml
rename it as .travis.yml and put in the root of your github directory.
Go to:
https://travis-ci.org/profile/modle-mod_quest
Flick the switch for this repo.

then on every commit you make to github it will fire off a request to travis to run the tests in .travis.yml and will give you traffic lights beside each commit and generate a report.

something else you might want to change:
in .travis.yml the default file has this line:

env:
global:

MOODLE_BRANCH=MOODLE_32_STABLE
you might want to add other branches to that list (or remove 32_STABLE because it's not supported.) so you might want to change it something like:

env:
global:

MOODLE_BRANCH=MOODLE_33_STABLE
MOODLE_BRANCH=MOODLE_34_STABLE
MOODLE_BRANCH=MOODLE_35_STABLE
doing it now makes it much easier for us to review your code.

**Comment by juacas** [comment]
MOODLE Versions updated.
