### ISSUE TITLE
copy of lib/graphlib.php in vendor directory.

### ISSUE THREAD

**Issue by danmarsden** [juacas/moodle-mod_quest#13]
the Vendor directory is often used for 3rd libraries, but this isn't really a 3rd party lib - it seems to be a copy of the existing lib/graphlib.php class - it would be better to put this into a "classes" folder rather than using Vendor and you should really rename the class to something like quest_graph if it is different from the core graph class to prevent it clashing with the core class.

Can you please move this out of the vendor directory and into a "classes" directory and rename the class? - it would also be a good idea to add some comments to the top of the file to state why you are using a different class - if you are only overriding 1 or 2 functions, it would be better to create a class that extends the core graph class and just includes the different functions to override the core ones rather than just copying the whole class.

**Comment by juacas** [comment]
Moved to classes folder. The history of this lib is too old to trace changes up to the current graphlib.php version.

**Comment by juacas** [comment]
I placed a little bit of work on it.  :ç
Now the class extends the only methods modified and the rest of the code ir removed. I hope the base graph class don't change in the near future.
Thanks for your effort and patience.

**Comment by danmarsden** [comment]
nice! - that looks a lot better than the previous code! - it should also make it much easier for you to mantain.
