### ISSUE TITLE
calls to deprecated function print_header_simple

### ISSUE THREAD

**Issue by danmarsden** [juacas/moodle-mod_quest#14]
print_header_simple has been gone since Moodle 2.6  - these calls will cause a fatal error in current versions of Moodle. Please update to using the new header functions.

found them in answer.php, calification.php uploadanswer.php

**Comment by juacas** [comment]
Dead code removed.

**Comment by danmarsden** [comment]
Looks like you've missed some of these - can you please re-check?

**Comment by danmarsden** [comment]
scrap that - I think I saw them in the master branch but you've put your patches into the new develop branch.
