### ISSUE TITLE
English language strings are not available in AMOS.

### ISSUE THREAD

**Issue by germanvaleroelizondo** [juacas/moodle-mod_quest#24]
Hi,
Firstly, I would like to congratulate you on this great new Moodle plugin. ¡Felicitaciones!

I wanted to translate your plugin into mexican Spanish (slightly different from the Spanish language used in Spain).

But, AMOS does not have your plugin English language strings available for translation for ANY language.

This is usually a coding error; the most common has been string concatenation, valid for regular PHP but prohibited by AMOS.

Please see https://docs.moodle.org/dev/Translating_plugins#Plugins_with_coding_errors .

By the way, nowadays there is no need to host language translation (besides English) for the string variables in the lang folder of the plugin, unless you want to override AMOS human translators. 

As soon as the English language strings for your plugin are recognized by AMOS, you (or any AMOS translator) can submit the translations into AMOS for regular processing.

Can you please check carefully the English language strings of quest.php and fix any concatenation of strings and any other coding error that might prevent AMOS from recognizing your strings ?

THANKS IN ADVANCE.

Also, I noticed a few Spanish words inside the English language strings of quest.php, as in line 224 'Se ha empleado el mecanismo de reclamaciones en la evaluación de una respuesta en' .

And there are a few words that may be inaccurate, such as 'Calification' which I assume in 'Marking' or 'Grading' as the proper translations of 'Calificación'.

I would like to suggest you to fist fix the coding errors in quest.php as described in the developer's documentation.

Then, I would be willing to check your Spanish and English strings and perhaps I might suggest a few minor changes in the English language strings, in order to make them more grammatically correct and friendlier for AMOS translators for other languages :)

Nuevamente, muchas felicitaciones por esta excelente contribución a Moodle :)

**Comment by juacas** [comment]
Thank you for your kind words.
I've checked the lang file and did not found any error (concatenations or similar) . However I made a lot of cleaning of unused strings.
Do you know if there is any error log to find out where the errors are in lang file?

**Comment by germanvaleroelizondo** [comment]
Thanks a lot for your quick fix for the contateniation issue.
AMOS now reports all 465 strings available for translation.

Can you please restore momentarily restore here i GitHub the es translation, which I presume is your original draft.

**Comment by juacas** [comment]
I'm not sure what you want. Do you want the Spanish language file?
You can get it from this git in releases v1.4.1 or older.
Also you would like to know that the strings are already imported into AMOS for international Spanish, Maybe still under review.
If I did not get your point, just elaborate your request a bit.

Regards

**Comment by juacas** [comment]
Please, note that the spanish language file is not cleaned and may contain many "dead strings" (unused in the current code).
Maybe you'd prefer to wait to the approval of the Spanish language package by the reviewers.

Good weekend.

**Comment by germanvaleroelizondo** [comment]
Hi,
The internatial Spanish language pack maintainers usually take a long time to review and approve a user contribution. That is why I wanted to have a look at your translated strings.

I have already translated into mexican Spanish 450 strings for your plugin, but I still need to translate 50 of the longest strings, and they are VERY large strings. So, I thought that maybe I could speed things a lot by looking at your Spanish version of the strings :)

**Comment by germanvaleroelizondo** [comment]
I have completed the es_mx translation of strings for your plugin :)

**Comment by germanvaleroelizondo** [comment]
English language strings are available in AMOS. Close this issue as solved :)
