### ISSUE TITLE
QUESTOURnament Moodle Docs page

### ISSUE THREAD

**Issue by germanvaleroelizondo** [juacas/moodle-mod_quest#28]
Hi,
I hope you don't mind that I have created a Moodle Docs page at https://docs.moodle.org/35/en/QUESTOURnament_module.

This page will be linked by the 'Moodle Docs for this page' link at he bottom of a screen  that shows when a user is creating/editing a QUESTOURnament.

Please feel free to add/remove/change as you see fit.

It will be very good if you can help me to create a working step-by-step tutorial for producing a QUESTOURnament, It would be even better if we can re-create a working QUSTOURnament that your students at Valladolid have successfully used in the past. If you do not have the time for making this tutorial, perhaps you could send me a backup of a Moodle course that used one such QUESTOURnament, so that I can re-create if from there.

I am a lecturer in Veterinary pathology at UNAM (México) and I am very interested in using this plugin for my students, and making documentation pages in Moodle Docs that will allow Moodle translators to better use your plugin with languages other than English.

**Comment by juacas** [comment]
Of course, all the help is appreciated.
Please, feel free to document your experiences.
Regards.
