### ISSUE TITLE
Invalid SQL comparison

### ISSUE THREAD

**Issue by mudrd8mz** [juacas/moodle-mod_quest#3]
On non-MySQL databases, queries like this fail badly:

```
ERROR: operator does not exist: character varying = bigint
LINE 8: AND l.info = s.id AND u.id =...
^
HINT: No operator matches the given name and argument type(s).
```

It is not valid to compare integer columns with text columns. As far as I know, only MySQL is tolerant to this. But generally it is a flaw in the database tables design.

**Comment by juacas** [comment]
Fixed and tested (with Postgresql)
