### ISSUE TITLE
3 hard-wired English language strings should be changed into string variables

### ISSUE THREAD

**Issue by germanvaleroelizondo** [juacas/moodle-mod_quest#30]
Hi.

There are (at least) 3 hard-wired English language strings in this plugin:
Admin logs
Get technical logs
Full activity listing

This plugin would improve if this (and all other) hard-wired English language (constants) strings were changed into English language variables, and thus be available in AMOS.

These strings appear when a user click on the cogwheel within a QUESTournament .

![questournament hard wired english strings](https://user-images.githubusercontent.com/2671923/45505059-338e5500-b751-11e8-8f6c-3f26e782fa9a.png)

**Comment by germanvaleroelizondo** [comment]
Also, 'Password' is a hard-wired English language strings in the plugin settings page (see enclosed image).

![questournament hard wired english string 3](https://user-images.githubusercontent.com/2671923/45506374-9af9d400-b754-11e8-87aa-fdc1cf216f79.png)

**Comment by juacas** [comment]
Located and corrected in develop branch! These changes will go in the next maintenance release.
Thanks!

**Comment by germanvaleroelizondo** [comment]
Thanks Juan !

**Comment by germanvaleroelizondo** [comment]
I just tested your DEVELOP branch and the new variable strings do exist, but they do not show in my local server

![questournament hard wired english string43](https://user-images.githubusercontent.com/2671923/45560834-d0152d80-b80b-11e8-84f0-c0e0dcdf0d70.png)

**Comment by juacas** [comment]
Maybe you need to purge the caches.
If you have updated the source code via GIT, strings are not updated until caches are purged.

**Comment by germanvaleroelizondo** [comment]
Silly old me :(
![questournament harcoded strings are fixed now](https://user-images.githubusercontent.com/2671923/45631159-e87d8600-ba5f-11e8-98b4-afc3e0c36f2d.png)
