### ISSUE TITLE
Direct access to $_GET is not allowed

### ISSUE THREAD

**Issue by danmarsden** [juacas/moodle-mod_quest#4]
https://github.com/juacas/moodle-mod_quest/blob/ba151a01075457194bfe1b3187b95d0224fdf59a/index.php#L35

https://github.com/juacas/moodle-mod_quest/blob/ba151a01075457194bfe1b3187b95d0224fdf59a/getLogs.php#L41

https://github.com/juacas/moodle-mod_quest/blob/ba151a01075457194bfe1b3187b95d0224fdf59a/viewclasification.php#L53

please remove these and replace with optional_param calls and the specific parameters that need to be included.

**Comment by juacas** [comment]
Thanks for reporting this issue.

$thispageurl is used just to redirect the browser to the very same page in the near future independently of the number of parameters present. For example, including theme, lang or whatever.
Those parameters are never parsed nor used in database queries.
As this is intended to represent current query, is it not acceptable to capture all the query params in this scenario? Is there any other way?

**Comment by danmarsden** [comment]
direct calls to raw $_GET and $_POST should never be used - it makes it too hard for people to verify the code is safe, and makes it very easy for a developer to miss that cleaning is not performed. One of the first things that an external reviewer will check for is for any existing use of $_GET/$_POST/$_REQUEST - and if found will need to perform further investigation to see if an issue exists.

I'd be tempted to write a function that built the array using optional param calls if they all use the same params - but it shouldn't be too difficult to work out what params are in use by each page.

Your other changes are looking really good though! - nice work so far!!

**Comment by danmarsden** [comment]
btw - once you solve this one, feel free to upload the new code into the plugins db and flag as ready for review again - the other 2 remaining issues open here are not blockers to approval in the db.

**Comment by juacas** [comment]
Thank you very much for your advice. 
Now I think it is ready for the next phase.
The other issues will be worked out soon.
