### ISSUE TITLE
hardcoded mdl_ prefix used in sql calls

### ISSUE THREAD

**Issue by danmarsden** [juacas/moodle-mod_quest#6]
Please review your code for hardcoded uses of mdl_ and replace with the correct curly braces around the table names:

eg: 

https://github.com/juacas/moodle-mod_quest/blob/ba151a01075457194bfe1b3187b95d0224fdf59a/scores_lib.php#L186

(there may be other cases of this in your code.)

**Comment by danmarsden** [comment]
in fact - that function also calls "execute_sql" which I couldn't see in your code and isn't a valid core function either - I suspect this code can be removed as it is no longer required and has been there since your 1.9 version?

**Comment by juacas** [comment]
Fixed

**Comment by danmarsden** [comment]
doesn't look like you've dealt with this properly tbh - can't this function just be removed? - execute_sql() hasn't been a function since Moodle 1.9.

**Comment by juacas** [comment]
You're right. Sorry. Done.
